apiVersion: apps/v1
kind: Deployment
metadata:
  name: avg-springboot-starter-deployment
  labels:
    app: avg-springboot-starter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: avg-springboot-starter
  template:
    metadata:
      labels:
        app: avg-springboot-starter
    spec:
      containers:
        - name: avg-springboot-starter
          image: swrap/avg-springboot-starter:0.0.3
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: avg-springboot-starter-service
spec:
  selector:
    app: avg-springboot-starter
  ports:
    - protocol: TCP
      name: api
      port: 8080
      targetPort: 8080
---
apiVersion: v1
kind: Namespace
metadata:
  name: {{.Values.namespace}}